In [ ]:
shubham = input("Enter for shubham")
print(shubham)

Enter for shubhamdubey
dubey


In [ ]:
choice = input("Enter the choice\n")
a = int(input("Enter for digit 1\n"))
b = int(input("Enter for digit 2\n"))
if choice == "1":
  c=a+b
  print(c)
elif choice == "2":
  c=a-b
  print(c)
elif choice == "3":
  c=a*b
  print(c)
else :
  c=a/b
  print(c)





Enter the choice
3
Enter for digit 1
12
Enter for digit 2
23
276


In [ ]:
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]
high_temp_threshold = 26
high_temp_cities = [city for city in climate_data if city["temperature"]> high_temp_threshold]
print("cities with high temperature (> 26):")
for city in high_temp_cities:
  print(f"{city['city']} - {city['temperature']}C")
carbon_footprints = [city["carbon_footprint"] for city in climate_data]
avg_carbon_footprint = sum(carbon_footprints) / len(carbon_footprints)
print("Average carbon footprint:", avg_carbon_footprint)
#write a code to write the cityb with hoghest carbon carbon_footprint
highest_footprint_city = max(climate_data, key=lambda cityt: city["carbon_footprint"])
print(f"\nCity with the highest carbon footprint:")
print(f"{highest_footprint_city['city']} ={highest_footprint_city['carbon_footprint']} kg CO2")


energy_consumption = 1000
emission_factor = 0.475
carbon_footprint = calculate_carbon_footprint(energy_consumption, emission_factor)
print(f"carbon Footprint: {carbon_footprint} kg CO2")



cities with high temperature (> 26):
City B - 30C
City E - 28C
Average carbon footprint: 420.0

City with the highest carbon footprint:
City A =500 kg CO2


NameError: name 'calculate_carbon_footprint' is not defined

In [ ]:
leap_year = lambda year: (year % 4 == 0) and (year % 100 != 0 or year % 400 == 0)
year=int(input("Enter The year You Want To Check For Leap Year\n"))
print(leap_year(year))


Enter The year You Want To Check For Leap Year
2003
False


In [ ]:
import pandas as pd
renewable_sources = ["Solar","Wind","Hydropower","Geothermal","Biomass"]
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}
renewable_series = pd.Series(renewable_sources)
print("Renewable Energy Sources:")
print(renewable_series)
projects_df = pd.DataFrame(data)
#projects_df.head()
#projects_df.describe()


Renewable Energy Sources:
0         Solar
1          Wind
2    Hydropower
3    Geothermal
4       Biomass
dtype: object


In [ ]:
import pandas as pd

# Create DataFrame
projects_df = pd.DataFrame(data)

# Filter projects with capacity > 100 MW
high_capacity_projects = projects_df[projects_df['Capacity (MW)'] > 100]

# Display the result
print(high_capacity_projects)

#total_capacity = projects_df["Capacity (MW)"].sum()
#total_cost = projects_df["Cost of s"]
grouped_data = projects_df.groupby("Technology")["Capacity (MW)"].sum()
print("\nTotal Capacity by Technology:")
print(grouped_data)


          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022  

Total Capacity by Technology:
Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64


In [ ]:
import numpy as np
one_d_array = np.array([1,2,3])
print(one_d_array)

[1 2 3]


In [ ]:
one_d_array = np.array([[1,2,3],[5,8,9]])
print(one_d_array)
#one_d_array.shape
#one_d_array.ndim
#one_d_array.size
#one_d_array.dtype
one_d_array.itemsize



[[1 2 3]
 [5 8 9]]


8

In [ ]:
np.ones(3)
np.zeros(3)
np.random.random(3)
array = np.full((3,3),5)
print(array)
iarray = np.identity(5)
print(iarray)


[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
linspace=np.linspace(5,10,5)
print(linspace)

[ 5.    6.25  7.5   8.75 10.  ]


In [ ]:
num=np.array([11,22,33,44,55,66,77,88,99])
print(num[:])
print(num[:1])
print(num[:2])
print(num[:-1])


[11 22 33 44 55 66 77 88 99]
[11]
[11 22]
[11 22 33 44 55 66 77 88]


In [ ]:
str1 = str(input("Enter the String\n"))
rev = str1[::-1]
if(rev==str1):
  print("Entered String is palindrome")
else:
  print("String is bakwas")

Enter the String
renuka
String is bakwas


In [ ]:
ar1 = np.array([[1,2,3],[4,6,9]])
print(ar1.flatten('f'))

[1 4 2 6 3 9]


In [ ]:
energy = np.array([1200,3400,2900,1800,2500])
print(energy)
np.mean(energy)
print(np.std(energy))

[1200 3400 2900 1800 2500]
781.2809993849844


In [ ]:
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}
